### PR TITLE
exported icons

### PR DESCRIPTION
**Pull request by pdabrowsky**
https://app.asana.com/0/1202705605335915/1202705556385161/f

### CODE REVIEW

**Comment by pdabrowsky** [comment]
czy da się to jakoś szybko i ładnie wyeksportować od razu z nazwami?

**Comment by dominikx96** [comment]
> czy da się to jakoś szybko i ładnie wyeksportować od razu z nazwami?

@pdabrowsky I don't think so, also use English for GitHub conversations :)

**Review by dominikx96 — CHANGES_REQUESTED** [review]
- the `Vector-13.svg` name is not a friendly name
- use lower case for directory names if it's not a component folder
- replace colors in each svg with `currentColor` - it inherits a color from a parent so an icon is more reusable, read more here and describe why we should use a `currentColor` here: https://css-tricks.com/cascading-svg-fill-color/

**Comment by pdabrowsky** [comment]
We should use `currentColor` to fix common problem with svg, if we add it, it inherits parent color. We can use it to match svg color and text.

**Review by dominikx96 — CHANGES_REQUESTED** [review]
You've just added `currentColor` to the element root, you haven't replaced current color values inside the code. It doesn't work. You should seek existing hardcoded colors and replace them with `currentColor` :)

**Review by dominikx96 — CHANGES_REQUESTED** [review]
You don't need left and right icons, only one is enough. You can rotate it with CSS.
Also the `conversation1` icon looks weird 🤔

**Review by dominikx96 — CHANGES_REQUESTED** [review]
Please remove conversation-part and export a full icon

**Review by dominikx96 — CHANGES_REQUESTED** [review]
Replace white with currentColor in the conversation icon

**Review by dominikx96 — APPROVED** [review]

**Pull request merged**
